FROM openresty/openresty:1.27.1.2-12-centos

# Runtime dependencies
RUN yum -y install \
  bash \
  curl \
  diffutils \
  grep \
  openssl \
  sed

# Build dependencies.
RUN yum -y install make

# Dependencies for the release process.
RUN yum -y install git zip

# Test dependencies
RUN yum -y install epel-release && \
  yum -y install \
    gcc \
    git \
    lsof \
    lua \
    procps-ng \
    redis \
    sudo && \
  curl -fsSL -o /tmp/ngrok.tgz -k https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz && \
  tar -xzf /tmp/ngrok.tgz -C /usr/local/bin && \
  rm -f /tmp/ngrok.tgz

RUN mkdir /app
WORKDIR /app

COPY Makefile /app/Makefile
RUN git config --global url."https://github.com/".insteadOf git://github.com/
RUN make install-test-deps

ENV PATH="/tmp/resty-auto-ssl-test-luarocks/bin:${PATH}"
ENV LUA_PATH="/tmp/resty-auto-ssl-test-luarocks/share/lua/5.1/?.lua;/tmp/resty-auto-ssl-test-luarocks/share/lua/5.1/?/init.lua;${LUA_PATH}"
ENV LUA_CPATH="/tmp/resty-auto-ssl-test-luarocks/lib/lua/5.1/?.so;${LUA_CPATH}"

COPY . /app

CMD ["bash"]
