FROM openresty/openresty:1.31.1.1-jammy

ENV DEBIAN_FRONTEND noninteractive

# Runtime dependencies
RUN apt-get update && \
  apt-get -y install \
    bash \
    curl \
    diffutils \
    grep \
    openssl \
    sed

# Build dependencies.
RUN apt-get update && \
  apt-get -y install make

# Test dependencies
RUN apt-get update && \
  apt-get -y install \
    git \
    lsof \
    lua5.2 \
    redis-server \
    sudo \
    tzdata && \
  curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc | tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && \
  echo "deb https://ngrok-agent.s3.amazonaws.com bookworm main" | tee /etc/apt/sources.list.d/ngrok.list && \
  apt-get update && \
  apt-get -y install ngrok

RUN mkdir /app
WORKDIR /app

COPY Makefile /app/Makefile
RUN git config --global url."https://github.com/".insteadOf git://github.com/
RUN make install-test-deps

ENV PATH="/tmp/resty-auto-ssl-test-luarocks/bin:${PATH}"
ENV LUA_PATH="/tmp/resty-auto-ssl-test-luarocks/share/lua/5.1/?.lua;/tmp/resty-auto-ssl-test-luarocks/share/lua/5.1/?/init.lua;${LUA_PATH}"
ENV LUA_CPATH="/tmp/resty-auto-ssl-test-luarocks/lib/lua/5.1/?.so;${LUA_CPATH}"

COPY . /app

CMD ["bash"]
