FROM openresty/openresty:1.31-alpine-fat

RUN mkdir /app
WORKDIR /app

# Runtime dependencies
RUN apk add --no-cache \
    bash \
    curl \
    diffutils \
    grep \
    openssl \
    sed

# Build dependencies.
RUN apk add --no-cache \
  make

# Test dependencies
RUN apk add --no-cache \
    findutils \
    gcc \
    git \
    hexdump \
    lsof \
    lua5.1 \
    procps \
    redis \
    sudo \
    tzdata \
    wget && \
  curl -fsSL -o /usr/local/bin/cloudflared https://github.com/cloudflare/cloudflared/releases/download/2026.7.3/cloudflared-linux-amd64 && \
  chmod +x /usr/local/bin/cloudflared

COPY Makefile /app/Makefile
RUN git config --global url."https://github.com/".insteadOf git://github.com/
RUN make install-test-deps

ENV PATH="/tmp/resty-auto-ssl-test-luarocks/bin:${PATH}"
ENV LUA_PATH="/tmp/resty-auto-ssl-test-luarocks/share/lua/5.1/?.lua;/tmp/resty-auto-ssl-test-luarocks/share/lua/5.1/?/init.lua;${LUA_PATH}"
ENV LUA_CPATH="/tmp/resty-auto-ssl-test-luarocks/lib/lua/5.1/?.so;${LUA_CPATH}"

COPY . /app

CMD ["bash"]
